<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE note SYSTEM "Note.dtd"> -->

<!DOCTYPE note
[
    <!ELEMENT note (to,from,heading,body)>
    <!ELEMENT to (#PCDATA)>
    <!ELEMENT from (#PCDATA)>
    <!ELEMENT heading (#PCDATA)>
    <!ELEMENT body (sucess)>
    <!ELEMENT sucess (#PCDATA)>

]>

<note>
    <to>Mayank</to>
    <from>Shreshth</from>
    <heading>Kal Milte hai ?</heading>
    <body>
        <sucess> Ok  bhai..</sucess>
        <sucess> Nhi Bro...</sucess>
    </body>
</note>